/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.7.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string
export interface InstantiateMsg {
  mint_cost: Uint128
  native_denom: string
  owner: string
}
export type ExecuteMsg = {
  add_fuel: {
    ash_fee_rate: Decimal
    ash_fee_recipient: string
    denom: string
    fuel_fee_rate: Decimal
    fuel_fee_recipient: string
    subdenom: string
  }
} | {
  burn: {}
} | {
  update_config: {
    mint_cost?: Uint128 | null
    owner?: string | null
  }
} | {
  update_fuel_config: {
    ash_fee_rate?: Decimal | null
    ash_fee_recipient?: string | null
    fuel_denom: string
    fuel_fee_rate?: Decimal | null
    fuel_fee_recipient?: string | null
  }
}
export type Decimal = string
export type QueryMsg = {
  config: {}
} | {
  fuels: {
    fuel_denom?: string | null
    limit?: number | null
    start_after?: Addr | null
  }
} | {
  leaderboard: {
    fuel_denom: string
    limit?: number | null
    start_after?: Addr | null
  }
}
export type Addr = string
export interface Config {
  mint_cost: Uint128
  native_denom: string
  owner: Addr
}
export interface FuelsResponse {
  fuels: FuelConfig[]
}
export interface FuelConfig {
  ash_fee_rate: Decimal
  ash_fee_recipient: Addr
  denom: string
  fuel_fee_rate: Decimal
  fuel_fee_recipient: Addr
  subdenom: string
}
export interface LeaderboardResponse {
  fuel_denom: string
  leaderboard: Array<[Addr, Uint128]>
}
